# import to use randint()
import random

# variables for the name and question asked
name = "Bruno"
question = "How are we doing?"
answer = ""


# returns a number between 1 and 9
random_number = random.randint(1, 11)

# prints the number generated by the function
print(random_number)


# All the possibilities of the 8 Ball
if random_number == 1:
  answer = "Yes - definitely"
elif random_number == 2:
  answer = "It is decidedly so"
elif random_number == 3:
  answer = "Without a doubt"
elif random_number == 4:
  answer = "Reply hazy, try again"
elif random_number == 5:
  answer = "Ask again later"
elif random_number == 6:
  answer = "Better not tell you now"
elif random_number == 7:
  answer = "My sources say no"
elif random_number == 8:
  answer = "Outlook not so good"
elif random_number == 9:
  answer = "Very doubtful"
elif random_number == 10:
  answer = "It looks that way"
elif random_number == 11:
  answer = "I'm afraid not"
else:
  answer = "Error"

if name == "" and  question != "":
  print("Question:", question)
  print("Magic 8-Ball's answer:", answer)
elif question == "":
  print("We cannot answer that which was not asked.")
else:
  print(name, "asks:", question)
  print("Magic 8-Ball's answer:", answer)


